### ISSUE TITLE
ImportError: No module named _nfc

### ISSUE THREAD

**Issue by sk25649** [xantares/nfc-bindings#2]
i@raspberrypi ~/nfc_madness/nfc-bindings/python/examples $ python quick_start_example.py 
Traceback (most recent call last):
  File "quick_start_example.py", line 7, in <module>
    import nfc
  File "/home/pi/nfc_madness/nfc-bindings/python/examples/nfc.py", line 30, in <module>
    _nfc = swig_import_helper()
  File "/home/pi/nfc_madness/nfc-bindings/python/examples/nfc.py", line 22, in swig_import_helper
    import _nfc
ImportError: No module named _nfc

I am getting this while running examples...

**Comment by xantares** [comment]
you're not supposed to have a copy of nfc.py in /home/pi/nfc_madness/nfc-bindings/python/examples/
follow the installation instruction from the readme
